apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: with-baby-friendship
spec:
  selector:
    cluster: neo4j 
  ports:
  - port: 7474
    targetPort: 7474
    name: http
  - port: 7687
    targetPort: 7687
    name: bolt
  - port: 7688
    targetPort: 7688
    name: crc
  - port: 5000
    targetPort: 5000
    name: cdm
  - port: 6000
    targetPort: 6000
    name: ct
  - port: 7000
    targetPort: 7000
    name: cr
  clusterIP: None
