apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-1
  namespace: with-baby-friendship
spec:
  selector:
    matchLabels:
      app: neo4j-1
  serviceName: neo4j
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j-1
        cluster: neo4j
    spec:
      containers:
      - name: neo4j-1
        image: neo4j:5.1.0-enterprise
        ports:
        - containerPort: 7474
          name: http
        - containerPort: 7687
          name: bolt
        - containerPort: 7688
          name: crc
        - containerPort: 5000
          name: cdm
        - containerPort: 6000
          name: ct
        - containerPort: 7000
          name: cr
        volumeMounts:
        - name: data
          mountPath: /data
        env:
          - name: NEO4J_server_default__advertised__address
            value: neo4j-1-0.neo4j.with-baby-friendship
          - name: NEO4J_server_default__listen__address
            value: 0.0.0.0
          - name: NEO4J_dbms_cluster_discovery_endpoints
            value: neo4j-0-0.neo4j.with-baby-friendship, neo4j-1-0.neo4j.with-baby-friendship, neo4j-2-0.neo4j.with-baby-friendship, 
          - name: NEO4J_initial_dbms_default__primaries__count
            value: "3"
          - name: NEO4J_initial_dbms_default__secondaries__count
            value: "0"
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
          - name: NEO4J_AUTH
            value: neo4j/Wt20220523
          - name: NEO4J_server_config_strict__validation_enabled
            value: "false"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: neo4j
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
      
